# Generated by Django 4.0.3 on 2022-04-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
