# Generated by Django 4.0.3 on 2022-04-14 12:32

from django.db import migrations
import services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', services.models.UserManager()),
            ],
        ),
    ]
