# Generated by Django 4.0.3 on 2022-04-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_course_course_image_alter_course_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_outline',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
