# Generated by Django 4.0.3 on 2022-04-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_alter_course_course_outline_alter_course_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='Activate',
            new_name='activate',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Activation_Date',
            new_name='activation_Date',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Apply_Date',
            new_name='apply_date',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='Section_id',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='enrollment',
            old_name='User_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='Course_id',
            new_name='course',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='Section_end_Date',
            new_name='section_end_date',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='Section_start_Date',
            new_name='section_start_date',
        ),
        migrations.RenameField(
            model_name='section',
            old_name='Section_title',
            new_name='section_title',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='CNIC',
            new_name='cnic',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Contact',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Educational_Background',
            new_name='educational_background',
        ),
    ]
