# Generated by Django 4.0.3 on 2022-04-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_alter_enrollment_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='activate',
            field=models.CharField(choices=[('True', 'Active'), ('False', 'InActive')], max_length=50),
        ),
    ]
