# Generated by Django 4.0.3 on 2022-04-26 10:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_alter_enrollment_activate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrollment',
            old_name='activate',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='course',
            name='course_outline',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='section',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.course'),
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('course', 'section_title')},
        ),
    ]
