# Generated by Django 4.0.3 on 2022-04-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_course_price_currency_alter_course_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
