# Generated by Django 4.0.3 on 2022-05-10 06:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_course_price_course_price_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200)),
                ('pub_date', models.DateField(default=datetime.date(2022, 5, 10))),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.course')),
            ],
        ),
    ]
