# Generated by Django 4.0.3 on 2022-05-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(max_length=200),
        ),
    ]
