# Generated by Django 4.0.3 on 2022-05-10 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_review_pub_date_review_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='pub_date',
            field=models.DateField(default=datetime.date(2022, 5, 10)),
        ),
    ]
