# Generated by Django 4.0.3 on 2022-05-16 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_like_dislike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_dislike',
            name='dislike',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='like_dislike',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
