# Generated by Django 4.0.3 on 2022-05-16 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_alter_like_dislike_dislike_alter_like_dislike_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='dislike',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='like',
            field=models.IntegerField(null=True),
        ),
    ]
