# Generated by Django 4.0.3 on 2022-05-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0023_review_dislike_review_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='review',
            name='like',
        ),
    ]
