# Generated by Django 4.0.3 on 2022-05-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_remove_review_dislike_remove_review_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_dislike',
            name='dislike',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='like_dislike',
            name='like',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
