# Generated by Django 4.0.3 on 2022-05-17 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0026_alter_like_dislike_dislike_alter_like_dislike_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like_dislike',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.review'),
        ),
    ]
