# Generated by Django 4.0.3 on 2022-05-17 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0030_rename_reply_review_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='parent',
            new_name='reply',
        ),
    ]
