# Generated by Django 4.0.3 on 2022-05-17 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_rename_parent_review_reply'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='reply',
            new_name='parent',
        ),
        migrations.AddField(
            model_name='review',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50),
        ),
        migrations.DeleteModel(
            name='Like_Dislike',
        ),
    ]
