# Generated by Django 4.0.3 on 2022-05-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_rename_reply_review_parent_review_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(default='Anonymous', max_length=50, null=True),
        ),
    ]
