# Generated by Django 3.1.1 on 2022-07-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_auto_20220724_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Exert', 'Expert')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='total_enrollments',
            field=models.IntegerField(default=0),
        ),
    ]
