# Generated by Django 3.1.1 on 2022-07-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0037_section_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='seo_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_keywords',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='seo_title',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
