# Generated by Django 3.1.1 on 2022-07-31 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0041_auto_20220801_0117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='activation_Date',
        ),
        migrations.AddField(
            model_name='enrollment',
            name='activation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='apply_date',
            field=models.DateField(default=datetime.date(2022, 8, 1)),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'InActive')], max_length=50),
        ),
    ]
