# Generated by Django 3.1.1 on 2022-07-31 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0042_auto_20220801_0216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('user', 'section')},
        ),
    ]
