# Generated by Django 3.1.1 on 2022-07-31 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0043_auto_20220801_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='enrollment_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
