# Generated by Django 3.1.1 on 2022-07-31 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0044_section_enrollment_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(null=True, upload_to='images/services'),
        ),
    ]
