# Generated by Django 3.1.1 on 2022-07-31 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0046_section_enrollment_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='section_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED'), ('UPCOMING', 'UPCOMING')], default='OPEN', max_length=20),
        ),
    ]
