# Generated by Django 3.1.1 on 2022-07-31 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0047_section_section_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('CURRENT', 'CURRENT'), ('CLOSED', 'CLOSED'), ('UPCOMING', 'UPCOMING')], default='OPEN', max_length=20),
        ),
    ]
