# Generated by Django 3.1.1 on 2022-08-06 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_auto_20220806_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='avatar.png', upload_to='images/users'),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(upload_to='images/courses'),
        ),
    ]
