# Generated by Django 3.1.1 on 2022-08-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0054_auto_20220806_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='section_status',
            field=models.CharField(choices=[('OPEN', 'OPEN'), ('IN PROGRESS', 'IN PROGRESS'), ('CLOSED', 'CLOSED'), ('UPCOMING', 'UPCOMING')], default='OPEN', max_length=20),
        ),
    ]
