# Generated by Django 3.1.1 on 2022-08-06 19:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0057_auto_20220806_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='seo_title',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='apply_date',
            field=models.DateField(default=datetime.date(2022, 8, 7)),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('In Review', 'In Review'), ('Approved', 'Approved'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='In Review', max_length=50),
        ),
    ]
