# Generated by Django 3.1.1 on 2022-08-07 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0060_auto_20220807_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateField(null=True),
        ),
    ]
